### ISSUE TITLE
Wipe `space.taran` prefix from all packages

### ISSUE THREAD

**Issue by kirillt** [ARK-Builders/arklib-android#112]
Prefix `space.taran` reflects my personal domain and was used when the project started.
Now, we have website `www.ark-builders.dev`. Let's use `dev.arkbuilders` prefix everywhere.  

This request should display 0 entries:
https://github.com/search?q=org%3AARK-Builders%20space.taran&type=code

**Comment by kirillt** [comment]
arklib-android:
- #110

Navigator:
- https://github.com/ARK-Builders/ARK-Navigator/pull/387
- https://github.com/ARK-Builders/ARK-Navigator/pull/394
- https://github.com/ARK-Builders/ARK-Navigator/pull/393

Shelf:
- https://github.com/ARK-Builders/ARK-Shelf/pull/34

Memo:
- https://github.com/ARK-Builders/ARK-Memo/pull/20

**Comment by tuancoltech** [comment]
> arklib-android:
> 
> * [Folder structure changes to reflect new package name #110](https://github.com/ARK-Builders/arklib-android/pull/110)
> 
> Navigator:
> 
> * [Package renaming ARK-Navigator#387](https://github.com/ARK-Builders/ARK-Navigator/pull/387)
> * [[build errors] Correct package name for classes from arklib due to re… ARK-Navigator#394](https://github.com/ARK-Builders/ARK-Navigator/pull/394)
> * [Restructure project ARK-Navigator#393](https://github.com/ARK-Builders/ARK-Navigator/pull/393)
> 
> Shelf:
> 
> * [Package renaming ARK-Shelf#34](https://github.com/ARK-Builders/ARK-Shelf/pull/34)
> * [Rename package from space.taran to dev.arkbuilders. ARK-Shelf#36](https://github.com/ARK-Builders/ARK-Shelf/pull/36)
> 
> Memo:
> 
> * [Package renaming ARK-Memo#20](https://github.com/ARK-Builders/ARK-Memo/pull/20)

The PR for Memo is here:

https://github.com/ARK-Builders/ARK-Memo/pull/28

**Comment by tuancoltech** [comment]
@kirillt I guess we can close this issue now?
Is there any other app that we missed?

**Comment by kirillt** [comment]
@tuancoltech thanks, good work.

Only one [odd spot](https://github.com/ARK-Builders/arklib-android/blob/main/lib/src/test/java/dev/arkbuilders/arklib/user/tags/RootTagStorageTest.kt) left, not sure how it appeared:

[Searching in our organization](https://github.com/search?q=org%3AARK-Builders%20space.taran&type=code) results only in ARK Retouch Legacy and that odd spot in tests, I've pushed the fix:

- #121
