### ISSUE TITLE
[Bug] Folders disapear when tap on chevron button in root item

### ISSUE THREAD

**Issue by hieuwu** [ARK-Builders/arklib-android#150]
Folders disapear when tap on chevron button in root item

Video:

https://github.com/ARK-Builders/arklib-android/assets/43868345/7fe2f6c4-af59-47fa-ab42-b15f7c7fb23b

Expected:
The list should remain

**Comment by mdrlzy** [comment]
Replaced by https://github.com/ARK-Builders/ark-android/issues/68
