### ISSUE TITLE
TagStorage can get corrupted during writing

### ISSUE THREAD

**Issue by kirillt** [ARK-Builders/arklib-android#35]
Sometimes, the file serving as tag storage becomes corrupted:
```
...
117421-975209069:visa
92126-3414598226:hmm
60272-1305102029:music
34362-6340143
(END OF FILE)
```
In the example above, resource id isn't complete and no tags following.

In fact, there is even bigger problem: in such cases, half of the storage is lost. Thanks to backup mechanism the loss can be mitigated. However, this must not happen at all.

Atomic writing should be implemented.

**Comment by kirillt** [comment]
We need to explore possibilities to prevent "dirty writing". Atomic writing could be implemented like this:
1) Create temporary file with unique name (use standard Java/Kotlin methods to obtain it).
2) When writing is done, copy the temporary file into the storage file (`.ark/tags` in case of tags storage).
We also must ensure that no storage is written from several threads/coroutines simultaneously. Otherwise, only one of writes would succeed.

There could be other ways to implement this OR ready-made libraries.

**Comment by ShubertMunthali** [comment]
```persist``` may complete before ```setTags``` completes here https://github.com/ARK-Builders/ARK-Navigator/blob/56e01cbc32a79fd593e32b8c6fb7df5a8ad18fef/app/src/main/java/space/taran/arknavigator/mvp/model/repo/tags/PlainTagsStorage.kt#L106-L111
leading to incomplete write to file

**Comment by kirillt** [comment]
@ShubertMunthali what can cause this? It seems to me that `setTags` finishes before `persist` is called..

**Comment by ShubertMunthali** [comment]
We have two coroutines there, ```setTags``` is called in ```Dispatchers.IO``` scope while ```persist``` is called in ```launch``` which uses ```Dispatchers.Default``` scope

**Comment by kirillt** [comment]
Superseded by #69
